server:
  port: 8765
  max-http-header-size: 102400
  tomcat:
    uri-encoding: UTF-8
    max-http-post-size: 102400

spring:
  profiles:
    active: dev
  application:
    name: monkeyzicloud-gateway
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false



